using System.Windows;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;

namespace QwenWorkOverlay;
public partial class MainWindow : Window
{
    private readonly SettingsService _settings; private readonly AppLogger _log; private readonly AudioDeviceService _devices=new(); private readonly AudioDefaultDeviceGuard _deviceGuard; private readonly MixedAudioSession _audio; private readonly CaptureProtectionService _capture=new(); private readonly QwenAudioAdapter _adapter=new();
    private QwenPageAdapter? _page; private GlobalHotkeys? _hotkeys; private IntPtr _hwnd; private bool _clickThrough, _hidden;
    public MainWindow(SettingsService settings,AppLogger log) { InitializeComponent();_settings=settings;_log=log;_deviceGuard=new(_devices);_audio=new(_devices);Loaded+=OnLoaded;Closing+=OnClosing; }
    private async void OnLoaded(object sender,RoutedEventArgs e)
    {
        var s=_settings.Current; Width=s.Width;Height=s.Height;var pos=WindowStateNormalizer.Normalize(double.IsNaN(s.X)?100:s.X,double.IsNaN(s.Y)?100:s.Y,Width,Height,System.Windows.Forms.Screen.AllScreens);Left=pos.X;Top=pos.Y;Topmost=s.TopMost;
        _hwnd=new WindowInteropHelper(this).Handle;var source=HwndSource.FromHwnd(_hwnd);source?.AddHook(WindowProc); SetOpacity(s.Opacity); SetCapture(s.CaptureProtection);_hotkeys=new(HandleHotkey);_hotkeys.RightCtrlChanged+=RightCtrlChanged;
        try {_page=new QwenPageAdapter(Browser);await _page.InitializeAsync();await _adapter.InitializeAsync(Browser);StatusText.Text="Qwen ready · select an optional virtual mix output in Settings";_log.Info("WebView initialized");}catch(Exception ex){StatusText.Text="WebView failed: "+ex.Message;_log.Error("WebView initialization: "+ex.GetType().Name);}
    }
    private IntPtr WindowProc(IntPtr h,int msg,IntPtr w,IntPtr l,ref bool handled)
    { if(msg==Native.WM_NCHITTEST&&!_clickThrough){var p=System.Windows.Forms.Cursor.Position;var x=p.X-(int)Left;var y=p.Y-(int)Top;const int b=7;int v=x<b?(y<b?Native.HTTOPLEFT:y>ActualHeight-b?Native.HTBOTTOMLEFT:Native.HTLEFT):x>ActualWidth-b?(y<b?Native.HTTOPRIGHT:y>ActualHeight-b?Native.HTBOTTOMRIGHT:Native.HTRIGHT):y<b?Native.HTTOP:y>ActualHeight-b?Native.HTBOTTOM:Native.HTCLIENT;if(v!=Native.HTCLIENT){handled=true;return new IntPtr(v);}}return IntPtr.Zero; }
    private void HandleHotkey(int id) { Dispatcher.InvokeAsync(async ()=>{switch(id){case 1:ToggleHide();break;case 2:SetClickThrough(!_clickThrough);break;case 3:Topmost=!Topmost;_settings.Current.TopMost=Topmost;_settings.Save();UpdateStatus();break;case 4:SetCapture(!_capture.Active);break;case 5:SetOpacity(_settings.Current.Opacity+.05);break;case 6:SetOpacity(_settings.Current.Opacity-.05);break;case 7:var kind=ClipboardPolicy.Classify(System.Windows.Clipboard.ContainsText(),System.Windows.Clipboard.ContainsImage());if(kind==ClipboardPayloadKind.Text&&_page is not null)await _page.InsertClipboardTextAsync(System.Windows.Clipboard.GetText());else if(kind==ClipboardPayloadKind.Image)_page?.PasteClipboard();break;case 8:ShowDiagnostics();break;case 9:Toast(ScreenshotService.CaptureForegroundToClipboard()?"Screenshot copied":"Screenshot failed");break;case 10:Toast(ScreenshotService.CaptureMonitorToClipboard()?"Monitor screenshot copied":"Screenshot failed");break;}}); }
    private void RightCtrlChanged(bool down){Dispatcher.InvokeAsync(()=>{if(!_settings.Current.RightCtrlAudioEnabled)return;if(down){_audio.Start(_settings.Current.MicrophoneDeviceId,_settings.Current.LoopbackDeviceId,_settings.Current.VirtualMixOutputDeviceId,_settings.Current.MicGain,_settings.Current.SystemGain);Toast(_audio.Running?_audio.InjectionState:"Audio unavailable");_log.Info("Audio session start: "+_audio.InjectionState);}else{_audio.Stop();Toast("MIX capture off");_log.Info("Audio session stop");}});}
    private void SetOpacity(double value){value=Math.Clamp(value,.35,1);_settings.Current.Opacity=value; if(_hwnd!=IntPtr.Zero){var style=Native.GetWindowLong(_hwnd,Native.GWL_EXSTYLE);Native.SetWindowLong(_hwnd,Native.GWL_EXSTYLE,style|Native.WS_EX_LAYERED);Native.SetLayeredWindowAttributes(_hwnd,0,(byte)Math.Round(value*255),Native.LWA_ALPHA);}_settings.Save();UpdateStatus();}
    private void SetClickThrough(bool enabled){_clickThrough=enabled;var style=Native.GetWindowLong(_hwnd,Native.GWL_EXSTYLE);Native.SetWindowLong(_hwnd,Native.GWL_EXSTYLE,enabled?style|Native.WS_EX_TRANSPARENT:style&~Native.WS_EX_TRANSPARENT);ClickButton.Background=new SolidColorBrush(enabled?Colors.OrangeRed:System.Windows.Media.Color.FromRgb(48,55,67));UpdateStatus();}
    private void SetCapture(bool enabled){var ok=_capture.Set(_hwnd,enabled);_settings.Current.CaptureProtection=ok&&enabled;_settings.Save();PrivacyButton.Background=new SolidColorBrush(_capture.Active?Colors.ForestGreen:Colors.DarkRed);Toast(enabled?(ok?"Capture protection ON":"Capture protection FAILED"):"Capture protection OFF");UpdateStatus();}
    private void ToggleHide(){if(_hidden){Show();WindowState=WindowState.Normal;Activate();_hidden=false;}else{Hide();_hidden=true;}}
    private void UpdateStatus()=>StatusText.Text=$"{(_clickThrough?"CLICK THROUGH · ":"")}Opacity {Math.Round(_settings.Current.Opacity*100)}% · Topmost {(Topmost?"ON":"OFF")} · Privacy {(_capture.Active?"ON":"OFF")}";
    private void Toast(string text){StatusText.Text=text;}
    private void DragBar_MouseLeftButtonDown(object s,MouseButtonEventArgs e){if(e.ChangedButton==MouseButton.Left)DragMove();}
    private void Mix_Click(object s,RoutedEventArgs e)=>RightCtrlChanged(!_audio.Running); private void Click_Click(object s,RoutedEventArgs e)=>SetClickThrough(!_clickThrough); private void Privacy_Click(object s,RoutedEventArgs e)=>SetCapture(!_capture.Active); private void CaptureTest_Click(object s,RoutedEventArgs e)=>new CapturePrivacyTestWindow{Owner=this}.Show(); private void Minimize_Click(object s,RoutedEventArgs e)=>WindowState=WindowState.Minimized; private void Close_Click(object s,RoutedEventArgs e)=>Close();
    private void Settings_Click(object s,RoutedEventArgs e){new SettingsWindow(_settings,_devices){Owner=this}.ShowDialog();SetOpacity(_settings.Current.Opacity);Topmost=_settings.Current.TopMost;SetCapture(_settings.Current.CaptureProtection);}
    private void ShowDiagnostics(){var text=$"WebView: {(_page?.Ready==true?"READY":"FAILED")}\nQwen URL: https://qwen.ai/\nQwen Page Adapter: {(_page?.Ready==true?"READY":"PENDING")}\nQwen Audio Adapter: {_adapter.State}\nPhysical Microphone: {(_audio.MicrophoneReady?"READY":"IDLE")}\nSystem Loopback: {(_audio.LoopbackReady?"READY":"IDLE")}\nMixer: {(_audio.Running?"CAPTURING":"IDLE")}\nMixed Stream: {_audio.MixedFrames} frames rendered\nQwen Audio Injection: {_audio.InjectionState}\nCapture Protection: {(_capture.Active?"ON":"OFF/FAILED")}\nClick-through: {_clickThrough}\nTopMost: {Topmost}\nDefault input: {_deviceGuard.InputBefore}\nDefault communications input: {_deviceGuard.CommunicationsBefore}\nDefault output: {_deviceGuard.OutputBefore}\nDefault communications output: {_deviceGuard.CommunicationsOutputBefore}";System.Windows.MessageBox.Show(this,text,"Qwen Work Overlay Diagnostics",MessageBoxButton.OK,MessageBoxImage.Information);}
    private void OnClosing(object? sender,System.ComponentModel.CancelEventArgs e){_audio.Stop();_settings.Current.X=Left;_settings.Current.Y=Top;_settings.Current.Width=Width;_settings.Current.Height=Height;_settings.Current.MonitorDeviceName=System.Windows.Forms.Screen.FromHandle(_hwnd).DeviceName;_settings.Save();var safe=_deviceGuard.Verify(_devices);_log.Info("Shutdown; audio default devices unchanged="+safe);_hotkeys?.Dispose();_devices.Dispose();_log.Info("Shutdown complete");}
}
